name: PR-Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'
    paths:
      - 'server2.js' 
    types: [opened, reopened, closed]

jobs:
  freeze-merge:
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - name: Freeze merge
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ github.base_ref }}/protection \
            -d '{"required_status_checks":null,"enforce_admins":true,"required_pull_request_reviews":null,"restrictions":{"users":[],"teams":[]}}'

  PR-lint-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: List files PR_lint
        run : ls -al  
      
      - name: Set up Node.js..
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      - name: Install dependencies.
        run: npm ci 
  unfreeze-merge:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Unfreeze merge
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -X DELETE \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ github.base_ref }}/protection
