name: PR workflow for server2.js

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:

  PR-lint-and-deploy-server2:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -al  
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci
