name: PR workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'

jobs:

  PR-lint-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      checks: write   # Permission to create a Check Run
      contents: write

    steps:
      - name: Create Check Run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/branches/${{ github.ref_name }}/protection \
          -d '{"required_status_checks":{"strict":true,"contexts":["PR-lint-and-deploy"]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":["octocat"],"teams":["justice-league"]},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2,"require_last_push_approval":true,"bypass_pull_request_allowances":{"users":["octocat"],"teams":["justice-league"]}},"restrictions":{"users":["octocat"],"teams":["justice-league"],"apps":["super-ci"]},"required_linear_history":true,"allow_force_pushes":true,"allow_deletions":true,"block_creations":true,"required_conversation_resolution":true,"lock_branch":true,"allow_fork_syncing":true}'

      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: List files
        run : ls -al  
      
      - name: Set up Node.js..
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      - name: Install dependencies.
        run: npm ci 
      
