name: PR workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'

jobs:

  PR-lint-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      checks: write   # Permission to create a Check Run
      contents: write

    steps:
      - name: Create Check Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{"name":"A Mighty Test", "head_sha":"${{ github.event.pull_request.head.sha }}", "status":"in_progress","output":{"title":"A Mighty Summary"}}' 
                  }'

      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: List files
        run : ls -al  
      
      - name: Set up Node.js..
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      - name: Install dependencies.
        run: npm ci 
      
